<!--include virtual="/include1/foot-global.inc" | FOOT - GLOBAL SCRIPTS -->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Bootstrap -->
    <script src="/js/bootstrap-4.5.2/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="/js/nav.min.js"></script>
    <!-- Back to Top script -->
    <script src="/js/back-to-top.min.js"></script>
    <!-- Google Tag Manager -->
    <script src="/js/google.tag.manager.min.js"></script>
    <!-- Google Analytics -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.min.js"></script>