    <footer class="container-fluid footer">
        <button id="back-to-top" title="Back to Top" class="read-more"><span class="glyphicon glyphicon-arrow-up" aria-hidden="true"></span>&nbsp;Back to Top</button>
        <div class="container">
            <div class="row"><!--links, emblem-->
                <div class="col-xs-6 col-md-3">
                    <p class="footer-links"><a href="/backmatter/email_update.html">Subscribe</a><br />
                    <a href="/backmatter/survey.html">Website Satisfaction Survey</a><br />
                    <a href="/backmatter/contactus.html">Contact Us</a><br />
                    <a href="/backmatter/contactus.html">Report an Error</a></p>
                </div>
                <div class="col-xs-6 col-md-3">
                    <p class="footer-links"><a href="/sitemap.html">Site Index</a><br />
                    <a href="/privacy.html">Privacy Policy</a><br />
                    <a href="/backmatter/disclaimer.html">Disclaimer</a><br />
                    <a href="/backmatter/siteinfo.html">Site Info</a></p>
                </div>
                <div class="col-xs-12 col-md-3">
                </div>
                <div class="col-xs-12 col-md-3">
                    <a href="/welcome.html"><img src="/images/oer_logo_white.png" alt="NOAA Office of Ocean Exploration and Research" class="img-responsive footer-emblem"></a>
                    <div class="social-links">
                        <a href="https://www.facebook.com/OceanExplorationResearch" class="social-fb" target="_blank"><img src="/images/social/facebook.svg" alt="Facebook" /></a>
                        <a href="https://twitter.com/oceanexplorer" class="social-tw" target="_blank"><img src="/images/social/twitter.svg" alt="Twitter" /></a> <a href="https://www.instagram.com/noaaoceanexploration/" class="social-ig" target="_blank"><img src="/images/social/instagram.svg" alt="Instagram" /></a>
                        <a href="https://www.youtube.com/oceanexplorergov" class="social-yt" target="_blank"><img src="/images/social/youtube.svg" alt="YouTube" /></a>

                    </div><!--end social-links-->
                </div>
            </div>
            <div class="row"><!--required-->
                <div class="col-xs-12 footer-bottom">
                    <div class="footer-logos">
                        <a href="http://www.noaa.gov/"><img src="/images/noaa_logo.png" alt="National Oceanic and Atmospheric Administration"></a>
                        &nbsp;
                        <a href="https://www.commerce.gov/"><img src="/images/doc_logo.png" alt="U.S. Department of Commerce"></a>
                    </div>
                    <div class="footer-text">
                        <p class="footer-links"> <a href="/welcome.html">Office of Ocean Exploration and Research</a><br />
                        <a href="http://www.noaa.gov/">National Oceanic and Atmospheric Administration</a><br />
                        <a href="https://www.commerce.gov/">U.S. Department of Commerce</a></p>
                    </div>
                </div>
            </div><!--end required-->
        </div>
    </footer>
    <noscript>This page requires you to have Javascript enabled.</noscript>