<!-- build:js(/Volumes/Chases/noaa/) foot-activmap.combined.min.js -->
    <!-- FOOT - ACTIVMAP -->
    <!-- MAP -->
        <!-- <script src="/js/jquery-activmap/1.7.1/jquery-activmap.min.js"></script> -->
        <!-- <script src="/js/jquery-activmap/1.7.1/markercluster.min.js"></script> -->
    <script src="/js/jquery-activmap.min.js"></script>
    <script src="/js/markercluster.min.js"></script>
    <!-- endbuild -->
    <script src="https://maps.googleapis.com/maps/api/js?libraries=visualization&v=3&client=gme-noaa&channel=OAR.OER.APP.Test"></script>