<!-- build:js(/Volumes/Chases/noaa/) foot-portfolio.combined.min.js -->    
     <!--FOOT - PORTFOLIO - PHOTOLOG STYLE -->  
     <!-- CBP -->  
          <!-- <script src="/js/cubeportfolio/4.4.0/jquery.cubeportfolio.min.js"></script> -->
          <!-- <script src="/js/cubeportfolio/4.4.0/cbp-init.min.js"></script> -->
     <script src="/cubeportfolio/js/jquery.cubeportfolio.4.4.0.min.js"></script>
     <script src="/js/cbp-init.min.js"></script>
     <!-- endbuild -->