<!-- build:js(/Volumes/Chases/noaa/) foot-dailyfolio.combined.min.js -->    
     <!--FOOT - PORTFOLIO - DAILYUPDATES STYLE -->  
     <!-- CBP -->  
           <!-- <script src="/js/cubeportfolio/4.4.0/jquery.cubeportfolio.min.js"></script> -->
           <!-- <script src="/js/cubeportfolio/4.4.0/cbp-init.min.js"></script> -->
     <script src="/cubeportfolio/js/jquery.cubeportfolio.min.js"></script>
     <script src="/js/cbp-init.min.js"></script>
     <!-- endbuild -->