<!-- build:js(/Volumes/Chases/noaa/) head-video.combined.min.js -->
    <!-- HEAD JWP VIDEO -->  
    <!-- jQuery -->
        <!-- <script src="/js/jquery/1.11.3/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- JWPlayer -->
        <!-- <script src="/js/jwplayer/5.0.0/jwplayer.min.js"></script> -->
    <script src="/js/jwplayer.min.js"></script>
    <!-- endbuild -->
    <script>jwplayer.key="Xn/dEFaxTQlMV6FC3sSXmvmPbX7BCdZdGOcUGey7Aos=";</script>