<!--include virtual="/include1/head-global.inc" | HEAD - GLOBAL STYLES -->
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap-5.0.0/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <!-- font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />