<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KJ4WK2P"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<header class="main-header">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-3 header-left">
				<a href="/welcome.html" class="logo"><img src="/images/oer_logo.png" alt="NOAA Office of Ocean Exploration and Research"></a>
			</div>
			<div class="col-sm-12 col-md-9 header-right">
                <form accept-charset="UTF-8" action="https://search.usa.gov/search" id="search_form" method="get">
                    <input name="utf8" type="hidden" value="&#x2713;" />
                    <input id="affiliate" name="affiliate" type="hidden" value="oceanexplorer.noaa.gov" />
                    <div class="col-sm-12 col-md-6 search-box">
                        <div class="input-group">
                            <input autocomplete="off" class="usagov-search-autocomplete form-control input-lg" id="query" name="query" type="text" placeholder="Search" />
                            <span class="input-group-btn">
                                <button class="btn btn-info btn-lg" type="button" title="Search" onclick="submit();">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </form>
			</div>
		</div><!--.row-->
	</div><!--.container-->
</header><!--.main-header-->

<nav class="navbar mainmenu">
		<div class="container">
		  	<div class="navbar-header">
		  		<button type="button" data-toggle="collapse" class="navbar-toggle collapsed" data-target="#oe-navbar-collapse" aria-expanded="false">
					<span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
					<span class="menu-text">Menu</span>
				</button>
			</div>

			<div class="collapse navbar-collapse oe-menu" id="oe-navbar-collapse">
			  <ul class="nav navbar-nav">

				<li class="menu-item "><a href="/welcome.html">Home</a></li>

				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/about/welcome.html">About OER&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/about/what-we-do/welcome.html" class="submenu-item">
								<span class="text">Our Mission<small>Activities, functions, &amp; capabilities </small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/about/staff.html" class="submenu-item">
								<span class="text">Who We Are<small>Organization &amp; staff contacts</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/about/partnerships/welcome.html" class="submenu-item">
								<span class="text">Partnerships<small>Who we work with</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="#" onclick='window.open("https://oeab.noaa.gov/");return false;' class="submenu-item">
								<span class="text">OEAB<small>Ocean Exploration Advisory Board</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/national-forum/welcome.html" class="submenu-item">
								<span class="text">National Forums<small>Annual ocean exploration forums</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/about/funding-opps/welcome.html" class="submenu-item">
								<span class="text">Funding Opportunities<small>OER call for proposals</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/about/exploration-opps/welcome.html" class="submenu-item">
								<span class="text">Exploration Opportunities<small>NOAA Ship <em>Okeanos Explorer</em> opportunities</small></span>
							</a>
						</li>
					</ul><!--.submenu-->
				</li>

				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/explorations/explorations.html">Expeditions&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/explorations/explorations-by-topic.html" class="submenu-item">
								<span class="text">By Topic<small>Browse expeditions by broad themes</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/explorations/location/explorations-by-location.html" class="submenu-item">
								<span class="text">By Location<small>Expeditions sorted by location</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/explorations/explorations-by-year.html" class="submenu-item">
								<span class="text">By Year<small>Browse expeditions by year</small></span>
							</a>
						</li>
					</ul><!--.submenu-->
				</li>

				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/technology/">Science &amp; Technology&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/okeanos/welcome.html" class="submenu-item">
								<span class="text"><em>Okeanos Explorer</em><small>About NOAA Ship <em>Okeanos Explorer</em></small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/technology/development-partnerships/development-partnerships.html" class="submenu-item ">
								<span class="text">Technology Development <small>OER technology projects</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/technology/technology.html" class="submenu-item ">
								<span class="text">Exploration Tools<small>Vessels, subs, and observation tools</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/history/history.html" class="submenu-item ">
								<span class="text">History of Ocean Exploration <small>Evolution of deep-ocean research</small></span>
							</a>
						</li>
					</ul><!--.submenu-->
				</li>

				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/data/">Data &amp; Products&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/data/access/access.html" class="submenu-item ">
								<span class="text">Data Access <small>Access expedition data </small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/okeanos/animal_guide/animal_guide.html" class="submenu-item ">
								<span class="text">Benthic Animal Guide <small>Collection of images for taxonomic reference</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/data/publications/welcome.html" class="submenu-item">
								<span class="text">Publications &amp; Reports<small>OER-related publications &amp; documents</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="#" onclick='window.open("https://docs.google.com/forms/d/e/1FAIpQLSdBLvbtStVhGrDO3Ugn_sNJpgR1Yy-e-DaUU3TIqGjg07lTNg/viewform?formkey=dHAycC1MYndJb0hTdGRaYXAzVTVBdWc6MA&fromEmail=true");return false;' class="submenu-item">
								<span class="text">Data Request Form<small>Request specific data</small></span>
							</a>
						</li>
					</ul><!--.submenu-->
				</li>


				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/edu/welcome.html">Education&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/okeanos/edu/welcome.html" class="submenu-item">
								<span class="text"><em>Okeanos</em> Education Materials<small><em>Okeanos Explorer</em> education content</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/edu/themes/welcome.html" class="submenu-item ">
								<span class="text">Themes <small>Education content organized by topic</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/edu/lessonplans/lessonplans.html" class="submenu-item">
								<span class="text">Lessons<small>Hands-on &amp; standards-based lesson plans</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/edu/modules/welcome.html" class="submenu-item">
								<span class="text">Expedition Education Modules<small>Education content for specific expeditions</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/edu/development/welcome.html" class="submenu-item">		
								<span class="text">Professional Development<small>Workshops &amp; webinars for educators</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/edu/careers.html" class="submenu-item">
								<span class="text">Careers &amp; Student Opportunities<small>Ocean exploration career options</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/facts/facts.html" class="submenu-item">
								<span class="text">Ocean Facts<small>Basic ocean information</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/edu/multimedia-resources/multimedia-resources.html" class="submenu-item">
								<span class="text">Multimedia Educational Resources <small>Interactive ocean information</small></span>
							</a>
						</li>
					</ul><!--.submenu-->
				</li>

				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/multimedia/">Multimedia&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/livestreams/welcome.html" class="submenu-item">
								<span class="text">Live Video<small>Live from <em>Okeanos Explorer</em></small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/video_playlist.html" class="submenu-item ">
								<span class="text">Video Playlists <small>Topical playlists of expedition videos</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/image-gallery/welcome.html" class="submenu-item">
								<span class="text">Image Gallery<small>Expedition images</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/multimedia/daily-image/welcome.html" class="submenu-item">
								<span class="text">Image of the Day Gallery<small>Daily image archive</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/forfun/wallpaper/welcome.html" class="submenu-item">
								<span class="text">Desktop Wallpaper<small>Deep-sea images for desktop display</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/forfun/wallpaper-calendar/welcome.html" class="submenu-item">
								<span class="text">Desktop Wallpaper Calendar<small>Monthly wallpaper calendar</small></span>
							</a>
						</li>
                        <li class="submenu-box">
							<a href="/multimedia/webinars/welcome.html" class="submenu-item">
								<span class="text">Webinars<small>Archived webinars</small></span>
							</a>
						</li>
                        <li class="submenu-box">
							<a href="/multimedia/video-shorts/welcome.html" class="submenu-item">								
								<span class="text">Social Media<small>Video Shorts</small></span>
							</a>
						</li>						
					</ul><!--.submenu-->
				</li>

				<li class="menu-item dropdown"><a class="dropdown-toggle" data-hover="dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/news">News&nbsp;<i class="glyphicon glyphicon-triangle-bottom"></i></a>
					<ul class="dropdown-menu submenu">
						<li class="submenu-box">
							<a href="/news/media-kit.html" class="submenu-item">
								<span class="text">Media Kit<small>Resources for members of the media</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/news/oer-updates/" class="submenu-item ">
								<span class="text">OER Updates <small>Office announcements &amp; accomplishments</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/news/oceanexplorationnews/" class="submenu-item">
								<span class="text">Ocean Exploration News<small>News from the exploration community</small></span>
							</a>
						</li>
						<li class="submenu-box">
							<a href="/news/exploration-extras/" class="submenu-item">
								<span class="text">Exploration Extras<small>Multimedia-rich features</small></span>
							</a>
						</li>
					</ul><!--.submenu-->
				</li>

			</ul>
		</div><!--oe-menu-->
	</div><!--container-->
</nav><!--.mainmenu-->