<!--include virtual="/include1/superfoot-dayfolio-map.inc" | FOOT - PORTFOLIO - DAILYUPDATES STYLE - MAP - NO VIDEO (dailyupdates with dives) -->
    <!-- Global Scripts -->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Bootstrap -->
    <script src="/js/bootstrap.js"></script>
    <script src="/js/bootstrap-hover-dropdown.js"></script>
    <script src="/js/nav.js"></script>
    <!-- Back to Top script -->
    <script src="/js/back-to-top.js"></script>
    <!-- Google Tag Manager -->
    <script src="/js/google.tag.manager.js"></script>
    <!-- Google Analytics -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.js"></script>
    <!-- CBP -->  
     <script src="/cubeportfolio/js/jquery.cubeportfolio.js"></script>
     <script src="/js/cbp-init.js"></script>
    <!-- MAP -->
    <script src="/js/jquery-activmap.js"></script>
    <script src="/js/markercluster.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?libraries=visualization&v=3&client=gme-noaa&channel=OAR.OER.APP.Test"></script>
    <script src="include/places.js"></script>
