<!--include virtual="/include1/superhead-video-map.inc" | HEAD - VIDEO - MAP - NO PORTFOLIO (welcome - jwplayer - with dives) -->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- JWPlayer -->
    <script src="/js/jwplayer.js"></script>
    <script>jwplayer.key="Xn/dEFaxTQlMV6FC3sSXmvmPbX7BCdZdGOcUGey7Aos=";</script>
    <!-- Map -->
    <link rel="stylesheet" href="/css/jquery-activmap.css" />
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />