<!-- build:js(/Volumes/Chases/noaa/) superfoot-portfolio-videojs.combined.min.js -->
    <!-- FOOT - PORTFOLIO - VIDEO - NO MAP (photolog - videojs) -->
    <!-- VideoJS -->
        <!-- <script src="/js/video-js/7.6.6/video.min.js"></script> --> 
        <!-- <script src="/js/video-js/7.6.6/videojs-resolution-switcher.min.js"></script> --> 
        <!-- <script src="/js/video-js/7.6.6/videojs-init.min.js"></script> --> 
    <script src="/js/video.min.js"></script>
    <script src="/js/videojs-resolution-switcher.min.js"></script>
    <script src="/js/videojs-init.min.js"></script>
    <!-- Global Scripts -->   
    <!-- jQuery -->
        <!-- <script src="/js/jquery/1.11.3/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Bootstrap -->
        <!-- <script src="/js/bootstrap/3.3.7/bootstrap.min.js"></script> -->
        <!-- <script src="/js/bootstrap/3.3.7/bootstrap-hover-dropdown.min.js"></script> -->
        <!-- <script src="/js/jquery/jquery.nav.min.js"></script> -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="/js/nav.min.js"></script>
    <!-- Back to Top script -->
        <!-- <script src="/js/utilities/back-to-top.min.js"></script> -->
    <script src="/js/back-to-top.min.js"></script>
    <!-- Google Tag Manager -->
        <!-- <script src="/js/utilities/google.tag.manager.min.js"></script> -->
    <script src="/js/google.tag.manager.min.js"></script>
    <!-- Google Analytics -->
        <!-- <script id="_fed_an_ua_tag" src="/js/utilities/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script> -->
        <!-- <script src="/js/utilities/google.analytics.min.js"></script> -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.min.js"></script>  
    <!-- CBP -->  
        <!-- <script src="/js/cubeportfolio/4.4.0/jquery.cubeportfolio.min.js"></script> -->
        <!-- <script src="/js/cubeportfolio/4.4.0/cbp-init-vjs.min.js"></script> -->
    <script src="/cubeportfolio/js/jquery.cubeportfolio.4.4.0.min.js"></script>
    <script src="/js/cbp-init-vjs.min.js"></script>
    <!-- endbuild -->