<!--include virtual="/include1/superhead-videojs-map.inc" | HEAD - VIDEO - MAP - NO PORTFOLIO (welcome - videojs - with dives) -->
    <link rel="stylesheet" href="/css/video-js.min.css"/>
    <link rel="stylesheet" href="/css/videojs-resolution-switcher.min.css"/>
    <link rel="stylesheet" href="/css/videojs-oer.min.css"/>
    <!-- Map -->
    <link rel="stylesheet" href="/css/jquery-activmap.min.css" />  
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />