<!--include virtual="/include1/superfoot-videojs.inc" | FOOT - VIDEO - NO MAP - NO PORTFOLIO (general - videojs) -->
    <script src="/js/video.js"></script>
    <script src="/js/videojs-resolution-switcher.js"></script>
    <script src="/js/videojs-init.js"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Bootstrap -->
    <script src="/js/bootstrap.js"></script>
    <script src="/js/bootstrap-hover-dropdown.js"></script>
    <script src="/js/nav.js"></script>
    <!-- Back to Top script -->
    <script src="/js/back-to-top.js"></script>
    <!-- Google Tag Manager -->
    <script src="/js/google.tag.manager.js"></script>
    <!-- Google Analytics -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.js"></script>   