<!--include virtual="/include1/superhead-videojs.inc" | HEAD - VIDEO - NO MAP - NO PORTFOLIO (general - videojs) -->
    <!-- VideoJS -->
    <link rel="stylesheet" href="/css/video-js.css"/>
    <link rel="stylesheet" href="/css/videojs-resolution-switcher.css"/>
    <link rel="stylesheet" href="/css/videojs-oer.css"/>
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />