<!-- build:js(/Volumes/Chases/noaa/) superfoot-video-map.combined.min.js -->
    <!-- FOOT - VIDEO - MAP - NO PORTFOLIO (welcome - jwplayer - with dives) -->  
    <!-- Global Scripts -->   
    <!-- jQuery -->
        <!-- <script src="/js/jquery/1.11.3/jquery.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Bootstrap -->
        <!-- <script src="/js/bootstrap/3.3.7/bootstrap.min.js"></script> -->
        <!-- <script src="/js/bootstrap/3.3.7/bootstrap-hover-dropdown.min.js"></script> -->
        <!-- <script src="/js/jquery/jquery.nav.min.js"></script> -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="/js/nav.min.js"></script>
    <!-- Back to Top script -->
        <!-- <script src="/js/utilities/back-to-top.min.js"></script> -->
    <script src="/js/back-to-top.min.js"></script>
    <!-- Google Tag Manager -->
        <!-- <script src="/js/utilities/google.tag.manager.min.js"></script> -->
    <script src="/js/google.tag.manager.min.js"></script>
    <!-- Google Analytics -->
        <!-- <script id="_fed_an_ua_tag" src="/js/utilities/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script> -->
        <!-- <script src="/js/utilities/google.analytics.min.js"></script> -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.min.js"></script>
    <!-- MAP -->
        <!-- <script src="/js/jquery-activmap/1.7.1/jquery-activmap.min.js"></script> -->
        <!-- <script src="/js/jquery-activmap/1.7.1/markercluster.min.js"></script> -->
    <script src="/js/jquery-activmap.min.js"></script>
    <script src="/js/markercluster.min.js"></script>
    <!-- endbuild -->
    <script src="https://maps.googleapis.com/maps/api/js?libraries=visualization&v=3&client=gme-noaa&channel=OAR.OER.APP.Test"></script>