<!--include virtual="/include1/superfoot-portfolio-video.inc" | HEAD - PORTFOLIO - PHOTOLOG STYLE - VIDEO - NO MAP (photolog - jwplayer) -->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>
    <!-- JWPlayer -->
    <script src="/js/jwplayer.js"></script> 
    <script>jwplayer.key="Xn/dEFaxTQlMV6FC3sSXmvmPbX7BCdZdGOcUGey7Aos=";</script>
    <!-- CBP -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio.4.4.0.css">
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />