<!--include virtual="/include1/superhead-dayfolio.inc" | HEAD - PORTFOLIO - DAILYUPDATES STYLE - NO MAP - NO VIDEO (dailyupdates) -->
    <!-- CBP -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio_dailyupdates.min.css">
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />