<!--include virtual="/include1/superfoot-dayfolio-map.inc" | HEAD - PORTFOLIO - DAILYUPDATES STYLE - MAP - NO VIDEO (dailyupdates - with dives) -->
    <!-- CBP -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio_dailyupdates.css">
    <!-- Map -->
    <link rel="stylesheet" href="/css/jquery-activmap.css" />
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />