<!--include virtual="/include1/superfoot-portfolio-videojs.inc" | HEAD - PORTFOLIO - VIDEO - NO MAP (photolog - videojs) -->
    <!-- VideoJS -->
    <link rel="stylesheet" href="/css/video-js.css"/>
    <link rel="stylesheet" href="/css/videojs-resolution-switcher.css"/>
    <link rel="stylesheet" href="/css/videojs-oer.css"/>
    <!-- CBP -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio.4.4.0.css">
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/responsive.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />