<!-- build:js(/Volumes/Chases/noaa/) superfoot-video.combined.min.js -->
    <!-- FOOT - VIDEO - NO MAP - NO PORTFOLIO (general - jwplayer) -->
    <!-- Global Scripts -->   
    <!-- Bootstrap -->
        <!-- <script src="/js/bootstrap/3.3.7/bootstrap.min.js"></script> -->
        <!-- <script src="/js/bootstrap/3.3.7/bootstrap-hover-dropdown.min.js"></script> -->
        <!-- <script src="/js/jquery/jquery.nav.min.js"></script> -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="/js/nav.min.js"></script>
    <!-- Back to Top script -->
        <!-- <script src="/js/utilities/back-to-top.min.js"></script> -->
    <script src="/js/back-to-top.min.js"></script>
    <!-- Google Tag Manager -->
        <!-- <script src="/js/utilities/google.tag.manager.min.js"></script> -->
    <script src="/js/google.tag.manager.min.js"></script>
    <!-- Google Analytics -->
        <!-- <script id="_fed_an_ua_tag" src="/js/utilities/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script> -->
        <!-- <script src="/js/utilities/google.analytics.min.js"></script> -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.min.js"></script>
    <!-- JWPlayer -->
        <!-- <script src="/js/jwplayer/one-vid.min.js"></script> -->
    <script src="/js/one-vid.min.js"></script>    
    <!-- endbuild -->